# Generated by Django 5.1.4 on 2026-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='full_name_input',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ism (foydalanuvchi kiritgan)"),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan"),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha telefon raqam"),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Asosiy telefon raqam'),
        ),
    ]
