# Generated by Django 5.1.4 on 2026-08-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_full_name_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz', "🇺🇿 O'zbekcha"), ('ru', '🇷🇺 Русский')], default='uz', max_length=10, verbose_name='Tanlangan til'),
        ),
    ]
